/**
 * GENERATED by scripts/watercolours.mjs — do not edit by hand.
 *
 * Add paintings by dropping files into Watercolours/<Category>/<Series>/ and
 * running `node scripts/watercolours.mjs`. Series order and the nicer titles
 * live in that script.
 *
 * Not a case study — a gallery. Painting is on the CV under Outside work, and
 * it belongs on the site for the same reason: it says something true that the
 * product work cannot.
 */
export type Painting = {
  src: string;
  title?: string;
  note?: string;
};

export type Series = {
  id: string;
  name: string;
  blurb?: string;
  paintings: Painting[];
};

export type Category = {
  id: string;
  name: string;
  blurb?: string;
  paintings?: Painting[];
  series?: Series[];
};

export const watercolours: Category[] = [
  {
    id: "architecture",
    name: "Architecture",
    blurb: "Urban sketching, mostly on location.",
    series: [
      {
        id: "france",
        name: "France, Loire and castles",
        blurb: "A trip through the Loire and Brittany — the châteaux, and what was growing and standing around them.",
        paintings: [
          { src: "/watercolours/architecture/france/01-cedre-noir.jpg", title: "Cèdre Noir" },
          { src: "/watercolours/architecture/france/02-chambord.jpg", title: "Chambord" },
          { src: "/watercolours/architecture/france/03-chanonceau.jpg", title: "Chenonceau" },
          { src: "/watercolours/architecture/france/04-chaumont-sur-loire.jpg", title: "Chaumont sur Loire" },
          { src: "/watercolours/architecture/france/05-chateau-de-saumur.jpg", title: "Château de Saumur" },
          { src: "/watercolours/architecture/france/06-chateau-du-clos-luce.jpg", title: "Château du Clos Lucé" },
          { src: "/watercolours/architecture/france/07-great-elephant-from-nantes.jpg", title: "The Great Elephant, Nantes" },
          { src: "/watercolours/architecture/france/08-levazereau.jpg", title: "Le Vazereau" },
          { src: "/watercolours/architecture/france/09-pierre-bertrand-couly.jpg", title: "Pierre Bertrand Couly" },
        ],
      },
      {
        id: "sevilla",
        name: "Sevilla",
        blurb: "La Giralda, the Setas, and the park in between.",
        paintings: [
          { src: "/watercolours/architecture/sevilla/01-la-giralda-copy.jpg", title: "La Giralda" },
          { src: "/watercolours/architecture/sevilla/02-maria-luisa-park-copy.jpg", title: "Maria Luisa Park" },
          { src: "/watercolours/architecture/sevilla/03-setas-copy.jpg", title: "Setas" },
          { src: "/watercolours/architecture/sevilla/04-untitled-1-copy.jpg", title: "Untitled 1" },
        ],
      },
      {
        id: "malaga",
        name: "Málaga",
        blurb: "The city — its cathedral, its port and its light.",
        paintings: [
          { src: "/watercolours/architecture/malaga/01-centre-pompidou-malaga-copy.jpg", title: "Centre Pompidou Malaga" },
          { src: "/watercolours/architecture/malaga/02-fuente-del-rey-malaga-copy.jpg", title: "Fuente del Rey Malaga" },
          { src: "/watercolours/architecture/malaga/03-malaga-catedral-copy.jpg", title: "Malaga Catedral" },
          { src: "/watercolours/architecture/malaga/04-malaga-palmeral-de-las-sorpresas-copy.jpg", title: "Malaga Palmeral de las Sorpresas" },
          { src: "/watercolours/architecture/malaga/05-the-palacio-de-ferias-y-congresos-de-malaga-copy.jpg", title: "The Palacio de Ferias y Congresos de Málaga" },
          { src: "/watercolours/architecture/malaga/06-white-street-in-malaga-copy.jpg", title: "White street in Malaga" },
        ],
      },
      {
        id: "portugal",
        name: "Portugal",
        blurb: "Lisbon, on location.",
        paintings: [
          { src: "/watercolours/architecture/portugal/01-arco-de-rua-augusta-rocio-train-station-lisbon.jpg", title: "Arco da Rua Augusta" },
          { src: "/watercolours/architecture/portugal/02-cathedral-se-lisbon-copy.jpg", title: "Cathedral Se Lisbon" },
          { src: "/watercolours/architecture/portugal/03-se-cathedral.jpg", title: "Sé cathedral" },
          { src: "/watercolours/architecture/portugal/04-watercolour20250114-23141251.jpg", title: "Untitled" },
          { src: "/watercolours/architecture/portugal/05-watercolour20250114-23400642.jpg", title: "Untitled" },
          { src: "/watercolours/architecture/portugal/06-watercolour20250115-15125537.jpg", title: "Untitled" },
        ],
      },
      {
        id: "prague",
        name: "Prague",
        blurb: "March, and mostly indoors.",
        paintings: [
          { src: "/watercolours/architecture/prague/01-dox-copy.jpg", title: "DOX" },
          { src: "/watercolours/architecture/prague/02-emaus-monastery-copy.jpg", title: "Emaus Monastery" },
          { src: "/watercolours/architecture/prague/03-food-copy.jpg", title: "Food" },
        ],
      },
      {
        id: "new-york",
        name: "New York",
        paintings: [
          { src: "/watercolours/architecture/new-york/01-golden-gate-ramka.jpg", title: "Golden Gate" },
          { src: "/watercolours/architecture/new-york/02-guggenheim-museum-new-york-ramka.jpg", title: "Guggenheim Museum" },
        ],
      },
      {
        id: "cadiz-province",
        name: "Cádiz province",
        blurb: "Andalusia — the white towns and the hills behind them.",
        paintings: [
          { src: "/watercolours/architecture/cadiz-province/01-cathedral-in-jerez-magazine-copy.jpg", title: "Cathedral in Jerez Magazine" },
          { src: "/watercolours/architecture/cadiz-province/02-molinos-de-vejer-1-copy.jpg", title: "Molinos de Vejer 1" },
        ],
      },
    ],
  },
  {
    id: "birds",
    name: "Birds",
    paintings: [
      { src: "/watercolours/birds/01-flaming-na-krzesle-w-ramce-copy.jpg", title: "Flaming na krzesle" },
      { src: "/watercolours/birds/02-gaviota-i-monstera-copy.jpg", title: "Gaviota i monstera" },
      { src: "/watercolours/birds/03-glossy-ibis-mockup.jpg", title: "Glossy ibis" },
    ],
  },
  {
    id: "animals",
    name: "Animals",
    paintings: [
      { src: "/watercolours/animals/01-alejandro-w-ramce-4-copy.jpg", title: "Alejandro" },
      { src: "/watercolours/animals/02-carmela-horse-kiss-ramka-1.jpg", title: "Carmela, the kiss" },
      { src: "/watercolours/animals/03-carmela-mloda-na-siwym-koniu-4-copy.jpg", title: "Carmela mloda na siwym koniu 4" },
      { src: "/watercolours/animals/04-geneta-w-ramce-3-copy.jpg", title: "Geneta" },
      { src: "/watercolours/animals/05-tuna-squid-and-meduzas.jpg", title: "Tuna, squid and jellyfish" },
      { src: "/watercolours/animals/06-tunczyk-na-scianie-nad-sofa.jpg", title: "Tuna" },
      { src: "/watercolours/animals/07-orka-w-ramce-copy.jpg", title: "orka" },
    ],
  },
  {
    id: "people",
    name: "People",
    paintings: [
      { src: "/watercolours/people/01-eve-andrzej-2.jpg", title: "Eve and Andrzej" },
    ],
  },
];

/** Everything in a category, whether loose or in a series. */
export const countPaintings = (category: Category): number =>
  (category.paintings?.length ?? 0) +
  (category.series ?? []).reduce((n, s) => n + s.paintings.length, 0);
